module.exports = {
    name: "ru",
    "8ball_usage": "<вопрос>",
    "8ball_desc": "Задать вопрос магическому шару",
    "8ball_title": "Магический шар",
    "8ball_answer": "Ответ:",
    ascii_usage: "<текст>",
    ascii_desc: "Создает ASCII арт из текста",
    ascii_fail: "> :x: Не удалось конвертировать эту строку.",
    avatar_usage: "[ID, @упоминание, server, banner или splash]. Если не указано, будет выведен ваш аватар",
    avatar_desc: "Показывает аватар пользователя",
    server_no_icon: "> :x: У этого сервера нет иконки.",
    server_no_banner: "> :x: У этого сервера нет баннера.",
    server_no_splash: "> :x: У этого сервера нет фона приглашения.",
    icon: (name) => `Иконка сервера ${name}`,
    banner: (name) => `Баннер сервера ${name}`,
    splash: (name) => `Фон приглашения сервера ${name}`,
    user_not_found: "> :x: Пользователь не найден.",
    avatar: (name) => `Аватар пользователя ${name}`,
    balance_usage: "[ID or @mупоминание]. Если не указано, будет выведен ваш баланс",
    balance_desc: "Показывает баланс пользователя",
    balance: "Баланс",
    deposit: "Депозит",
    ban_usage: "<ID или @упоминание> [дни для очистки (1-7)] [причина]",
    ban_yourself: "> :x: Вы не можете забанить себя.",
    ban_bot: "> :x: Бот не может забанить себя.",
    no_reason: "Причина не указана",
    long_reason: "> :x: Причина слишком длинная.",
    ban_higher: "> :x: Вы не можете забанить участника, который выше вас.",
    banned: (name) => `${name} был забанен!`,
    reason: (text) => `Причина: ${text}`,
    ban_failed: "> :x: Не удалось забанить этого пользователя.",
    decode_usage: "<код>",
    decode_desc: "Декодирует закодированный текст",
    decode: "Декодирование",
    decode_error: "> :x: Можно декодировать только hex",
    deposit_desc: "Положить <:rscredit:767386949400657932> на депозит",
    invalid_amount: "> :x: Указано неверное количество.",
    deposit_success: "Успешно!",
    deposit_no_dep: (balance) => `:x: **У вас нет столько на депозите. Ваш депозит: ${Number(balance)} <:rscredit:767386949400657932>**`,
    no_bal: (balance) => `:x: **У вас нет столько денег. Ваш баланс: ${Number(balance)} <:rscredit:767386949400657932>**`,
    deposit_help: "Вы можете внести <:rscredit:767386949400657932> на депозит.\nПри этом вы не сможете их использовать (переводить, ставить ставки и эта сумма не будет учитываться в топах.) до того, как вы их снимете.\nКаждые 4 часа будет начисляться 1% от суммы на депозите (лимит 250000).",
    usage: "Использование",
    deposit_usage: (prefix, name) => `\`\`\`${prefix}${name} <wd or withdraw> <кол-во> - снять с депозита\n${prefix}${name} <put> <кол-во> - положить на депозит\`\`\``,
    dice_usage: "<ставка>",
    dice_desc: "Ставки в <:rscredit:767386949400657932>",
    dice_invalid_bet: "> :x: Указана неверная ставка.",
    casino: "Казино",
    dice_win: (amount, balance) => `:tada: **Вы выиграли ${amount}** <:rscredit:767386949400657932>. Ваш новый баланс: ${Number(balance)} <:rscredit:767386949400657932>`,
    dice_win_x4: (amount, balance) => `:tada::tada::tada: **Вы получили Х4 выигрыш!** Ваш новый баланс: ${Number(balance)} <:rscredit:767386949400657932>`,
    dice_lose: (amount, balance) => `**Вы проиграли ${amount}** <:rscredit:767386949400657932>. Ваш новый баланс: ${Number(balance)} <:rscredit:767386949400657932>`,
    distext_usage: "<число> <текст>",
    cmd_usage(prefix, cmd) { return `> :x: Используйте \`${prefix}${cmd.name} ${this[cmd.usage]}\``},
    distext: "Искажение текста",
    dsay_usage: "<текст или вложения>",
    embcolor_usage: "<reset, random или код цвета>",
    embcolor_desc: "Изменяет цвет эмбедов",
    embcolor_color: (color) => `Ваш цвет: ${color}`,
    embcolor_usage2(prefix, cmd) { return `Используйте ${prefix}${cmd.name} ${this[cmd.usage]} чтобы изменить свой цвет`},
    embcolor_reset: ":white_check_mark: **Цвет сброшен!**",
    embcolor_random: ":white_check_mark: **Цвет установлен на случайный!**",
    embcolor_error_t: ":x: Указан неверный цвет.",
    embcolor_error_d: "Example:\n`#123456`, `0x123456` или число от 1 до 16777215",
    embcolor_success: (color) => `:white_check_mark: **Цвет изменен на \`${color}\`!**`,
    encode_usage: "<текст>",
    encode_desc: "Кодирует английский текст",
    encode: "Кодирование",
    encode_tip: "Кодируются только английские буквы и цифры",
    help_usage: "[команда]",
    help_desc: "Показывает информацию о командах",
    help_cmd_not_found: "> :x: Такой команды не существует.",
    help_info: (name) => `Информация о команде \`${name}\``,
    desc: "Описание",
    aliases: "Алиасы",
    no: "Нет",
    help_list: "Список команд",
    help_embdesc(prefix, cmd){ return `Префикс: \`${prefix}\`\nДля получения информации о какой-либо команде используйте \`${prefix}${cmd.name} ${this[cmd.usage]}\``},
    help_ginfo: "Информационные",
    help_gfun: "Развлекательные",
    help_geco: "Экономика",
    help_gother: "Прочие",
    help_gmod: "Модераторские",
    help_gsets: "Настройки",
    invite_usage: "<инвайт-код/ссылка>",
    invite_desc: "Показывает информацию о приглашении",
    verLvl: ["Нет", "Низкий", "Средний", "Высокий", "Очень высокий"],
    guild_features: {
        INVITE_SPLASH: "фон приглашения",
        VIP_REGIONS: "384 кб/с голосовой канал",
        VANITY_URL: "свой инвайт-код",
        VERIFIED: "верифицированный сервер",
        PARTNERED: "партнерский сервер",
        PUBLIC: "публичный сервер",
        COMMERCE: "поммерческий сервер",
        NEWS: "новостной канал",
        DISCOVERABLE: "доступен в обзоре серверов",
        FEATURABLE: "предлагаемый сервер",
        ANIMATED_ICON: "анимированный значок",
        BANNER: "баннер",
        PUBLIC_DISABLED: "не может быть публичным",
        WELCOME_SCREEN_ENABLED: "экран приветствия",
        COMMUNITY: "сервер сообщества",
        MEMBER_VERIFICATION_GATE_ENABLED: "отбор участников",
        PREVIEW_ENABLED: "превью сервера"
    },
    owner: "Владелец",
    created: "Создан",
    days_ago: "дн. назад",
    members: "Участники",
    members_stats: (guild) => `Всего - ${guild.members.size}
Боты - ${guild.members.filter(m => m.user.bot).length}
                
Онлайн - ${guild.members.filter(m => m.status == "online").length}
Не активны - ${guild.members.filter(m => m.status == "idle").length}
Не беспокоить - ${guild.members.filter(m => m.status == "dnd").length}
Не в сети - ${guild.members.filter(m => m.status == "offline" || !m.status).length}`,
    channels: "Каналы",
    channels_stats: (guild) => `Всего - ${guild.channels.size}
            
Категории - ${guild.channels.filter(c => c.type == 4).length}
Текстовые - ${guild.channels.filter(c => c.type == 0).length}
Голосовые - ${guild.channels.filter(c => c.type == 2).length}
Новостные - ${guild.channels.filter(c => c.type == 5).length}`,
    emoji: "Эмодзи",
    emoji_stats: (guild) => `Всего - ${guild.emojis.length}
            
Анимированные - ${guild.emojis.filter(e => e.animated).length}
Статичные - ${guild.emojis.filter(e => !e.animated).length}`,
    roles: "Ролей",
    region: "Регион",
    modlvl: "Уровень модерации",
    features: "Функции",
    channel: "Канал",
    inviter: "Приглашающий",
    level: "уровень",
    boosts: "бустов",
    invite_error: "> :x: Такого приглашения не существует.",
    kick_usage: "<ID или @упоминание> [причина]",
    kick_yourself: "> :x: Вы не можете кикнуть себя.",
    kick_bot: "> :x: Бот не может кикнуть себя.",
    kick_higher: "> :x: Вы не можете кикнуть участника, который выше вас.",
    kicked: (name) => `${name} был кикнут!`,
    kick_failed: "> :x: Не удалось забанить этого пользователя.",
    links_desc: "Ссылки",
    links_invite: "Пригласить бота на сервер",
    clickable: "кликабельно",
    links_monitorings: "Мониторинги",
    links_source: "Исходный код",
    pay_usage: "<ID или @упоминание> <кол-во>",
    pay_desc: "Переводит деньги",
    pay_bot: "> :x: Вы не можете перевести деньги боту.",
    pay_yourself: "> :x: Вы не можете перевести деньги себе.",
    transfer: "Перевод",
    pay_success: (amount, name) => `:white_check_mark: **Переведено ${amount} <:rscredit:767386949400657932> пользователю ${name}**`,
    ping_usage: "[-v (пинг бота)]",
    ping_desc: "Показывает пинг бота",
    ping: "Пинг",
    ms: "мсек.",
    bot: "Бот",
    prefix_usage: "[новый префикс]",
    prefix_desc: "Изменяет префикс на сервере",
    prefix_embdesc: (prefix) => `Префикс на этом сервере - \`\`${prefix}\`\`\nИспользуйте \`${prefix}help\` для получения списка команд.`,
    prefix_tip(prefix, cmd){ return `Вы можете изменить префикс на сервере использовав ${prefix}${cmd.name} ${this[cmd.usage]}`},
    prefix_long: "> :x: Префикс не может быть длиннее 10 символов.",
    prefix_success: (prefix) => `> :white_check_mark: **Префикс изменен на** \`${prefix.toLowerCase()}\``,
    purge_usage: "<кол-во>",
    purge_desc: "Очищает сообщения",
    purge_invalid_amount: "> :x: Указано неверное кол-во сообщений для очистки. (используйте от 1 до 100)",
    purge_success: (deleted, arg) => `> :white_check_mark: **Удалено \`\`${deleted-1 == parseInt(arg) ? parseInt(arg) : deleted}\`\` сообщений. Это сообщение удалится через 5 секунд**`,
    random_usage: "[от] <до>",
    random_desc: "Генерирует случайное число",
    random: (args) => `Случайное число от ${!!args[1] ? parseInt(args[0], 10) : 0} до ${parseInt(args[1], 10) || parseInt(args[0], 10)}`,
    reverse_usage: "<текст>",
    reverse_desc: "Реверсирует текст",
    reverse: "Реверс",
    role_usage: "<ID или @упоминание>",
    default_color: "Стандартный",
    role_not_found: "> :x: Роль не найдена.",
    role_position: "Позиция",
    role_managed: "Управляется интеграцией?",
    yes: "Да",
    role_mentionable: "Упоминаемая?",
    role_hosted: "Показывется отдельно?",
    role_members: "Участники с этой ролью",
    na: "Не доступно",
    color: "Цвет",
    say_usage: "<текст и/или изображение>",
    server_desc: "Показывает информацию о сервере",
    softban_usage: "<ID или @упоминание> <дни для очистки (1-7)> [причина]",
    softban_desc: "Кикает участника и удаляет его сообщения",
    softban_yourself: "> :x: Вы не можете софтбанить себя.",
    softban_bot: "> :x: Бот не может софтбанить себя.",
    softban_higher: "> :x: Вы не можете софтбанить участника, который выше вас.",
    softbanned: (name) => `${name} был софтбанен!`,
    softban_failed: "> :x: Не удалось софтбанить этог опользователя.",
    softban_error: "> :x: Указано неверное кол-во дней (используйте от 1 до 7)",
    stats_usage: "[-v (больше информации)]",
    stats_desc: "Показывает статистику бота",
    stats: "Статистика",
    stats_uptime: "Аптайм",
    d: " дн. ",
    h: " ч. ",
    m: " мин. ",
    s: "сек. ",
    stats_uptime_c: "Аптайм (клиент)",
    stats_uptime_h: "Аптайм (хост)",
    stats_servers: "Сервера",
    stats_users: "Пользователи",
    stats_packages: "Использованные пакеты",
    stats_ram: "Использовано ОЗУ",
    mb: "МБ",
    stats_cpu: "Процессор",
    top_usage: "[-g (глобальный топ)]",
    top_desc: "Топ-10 пользователей по балансу",
    top_global: "Глобальный топ",
    top_place: (place, balance) => `Ваше место: ${place}, баланс: ${Number(balance)}`,
    top_balance: (balance) => `Ваш баланс: ${Number(balance)}`,
    top_server: (name) => `Топ сервера ${name}`,
    unwarn_usage: "<ID варна>",
    unwarn_desc: "Удаляет варн с пользователя",
    user_usage: "[ID или @упоминание]",
    user_desc: "Показывает информацию о пользователе",
    online: "Онлайн",
    idle: "Не активен",
    dnd: "Не беспокоить",
    offline: "Не в сети",
    invisible: "Невидимый",
    types: ["Играет в", "Стримит", "Слушает", "Смотрит", "Кастомный статус", "Соревнуется в"],
    user_bot: "Бот?",
    user_status: "Статус",
    user_registered: "Зарегистрировался",
    user_joined: "Присоединился к серверу",
    user_tops: "Позиции в топах",
    user_roles: "Роли",
    user_no_top: "не показывается в топе",
    global: "Глобальный топ",
    server: "Топ сервера",
    place: "место",
    ending: (index) => {
        if(index.toString().endsWith(2) && index != 12) return "ой"
        if(index.toString().endsWith(3) && index != 13) return "ий"
        if(index.toString().endsWith(6) && index != 16) return "ой"
        if(index.toString().endsWith(7) && index != 17) return "ой"
        if(index.toString().endsWith(8) && index != 18) return "ой"
        return "ый"
    },
    member: "участник сервера",
    warn_now_found: "> :x: Предупреждение не найдено.",
    unwarned: (name) => `Снято предупреждение с ${name}`,
    warn_usage: "<ID или @упоминание> [причина]",
    warn_yourself: "> :x: Вы не можете выдать предупреждение себе.",
    warn_bot: "> :x: Вы не можете выдать предупреждение боту.",
    warn_error: "> :x: У участника не может быть более 25 предупреждений.",
    warned: (warnid, name) => `Участнику ${name} выдано предупреждение! (ID: ${warnid})`,
    warns_usage: "[ID или @упоминание]",
    warns_desc: "Показывает предупреждения пользователя",
    warns: "Предупреждения",
    warns_mod: "Модератор",
    all: "Всего",
    work_desc: "Заработать <:rscredit:767386949400657932>",
    work_cooldown: (time) => `:x: **Работа будет доступна через ${time} минут**`,
    work_success: (worked, balance) => `Вы заработали ${worked} <:rscredit:767386949400657932>. Ваш баланс: ${Number(balance)} <:rscredit:767386949400657932>.`,
    work: "Работа",
    embed_error: "> :x: Бот должен иметь право `Встраивать ссылки`.",
    banMembers: "Банить участников",
    kickMembers: "Кикать участников",
    manageMessages: "Управлять сообщениями",
    manageGuild: "Управлять сервером",
    no_user_permission(permission){ return `> :x: Вы должны иметь право \`${this[permission]}\` чтобы использовать эту команду.`},
    no_bot_permission(permission){ return `> :x: Бот должен иметь право \`${this[permission]}\` чтобы использовать эту команду.`},
    cmd_error: "Произошла ошибка при выполнении команды",
    lang_usage: "[новый язык]",
    lang_desc: "Изменяет ваш язык",
    lang_embdesc: (client) => `Доступные языки: ${client.langs.map(l=>l.name).join(", ")}`,
    lang_tip(prefix, cmd){ return `Вы можете изменить язык использовав ${prefix}${cmd.name} ${this[cmd.usage]}`},
    lang_not_found: "> :x: Язык не найден."
}